### ISSUE TITLE
references

### ISSUE THREAD

**Issue by mametur** [mametur/mame-oguz-work#8]
### HTML

- aside element
- some links for people to learn more about the cool thing

### CSS

Styling for the new element

**Comment by snicoll** [comment]
@mametur @oguzkarademir This issue is closed by PR #9 but it is still open. It should be closed since that work has been merged to `master`. 

We've seen in class that this can happen automatically when you add `Closes #8` in the commit message (the best practice is to add that at the end of the commit message on its own line). There are three other issues in the same state in this repository.

Relates is more when you want to add a reference to an issue to provide additional context.

Let me know if you have any questions

**Comment by mametur** [comment]
@snicoll thank you so much for your feedback, now I have learnt  that  **`after merging to master issues should be close`**
